version: '3.3'

services:
  mqtt-broker:
    image: eclipse-mosquitto:1.6.9
    container_name: mqtt-broker
    ports:
      - 1883:1883
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - broker-adapter

  adapter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adapter
    depends_on:
      - mqtt-broker
    networks:
      - broker-adapter
      - influxdb-adapter
    environment:
      - DEBUG_DATA_FLOW=true

  influxdb:
    image: influxdb:1.8.0
    container_name: influxdb
    ports:
      - 8086:8086
    restart: always
    volumes:
      - database:/data/influxdb
    networks:
      - influxdb-adapter
      - influxdb-grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 80:3000
    networks:
      - influxdb-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana:/var/lib/grafana


networks:
  broker-adapter:
    name: broker_adapter
  influxdb-adapter:
    name: influxdb_adapter
  influxdb-grafana:
    name: influxdb_grafana

volumes:
  database: {}
  grafana: {}