version: '3.3'

services:
  mqtt-broker:
    image: eclipse-mosquitto:1.6.9
    container_name: mqtt-broker
    ports:
      - 1883:1883
    restart: always
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - broker-adapter

  adapter:
    image: adapter
    build:
      context: .
      dockerfile: ./adapter/Dockerfile
    container_name: adapter
    depends_on:
      - mqtt-broker
      - influxdb
    networks:
      - broker-adapter
      - influxdb-adapter
    environment:
      - DEBUG_DATA_FLOW=true

  influxdb:
    image: influxdb:1.8.0
    container_name: influxdb
    ports:
      - 8086:8086
    restart: always
    volumes:
      - database:/var/lib/influxdb
    networks:
      - influxdb-adapter
      - influxdb-grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 80:3000
    restart: always
    networks:
      - influxdb-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC
    volumes:
      - grafana-vol:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

networks:
  broker-adapter:
  influxdb-adapter:
  influxdb-grafana:

volumes:
  database: {}
  grafana-vol: {}