/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"

bool_t
xdr_token (XDR *xdrs, token *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->type, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->client_id, ~0))
		 return FALSE;
	 if (!xdr_token (xdrs, &objp->token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	 if (!xdr_token (xdrs, &objp->auto_token))
		 return FALSE;
	 if (!xdr_token (xdrs, &objp->access_token))
		 return FALSE;
	 if (!xdr_token (xdrs, &objp->refresh_token))
		 return FALSE;
	return TRUE;
}
