/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"

bool_t
xdr_tokken (XDR *xdrs, tokken *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->approved))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->type, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cl_request (XDR *xdrs, cl_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->user_index))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->info, ~0))
		 return FALSE;
	 if (!xdr_tokken (xdrs, &objp->tokken))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ser_response (XDR *xdrs, ser_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	 if (!xdr_tokken (xdrs, &objp->auto_token))
		 return FALSE;
	 if (!xdr_tokken (xdrs, &objp->access_token))
		 return FALSE;
	 if (!xdr_tokken (xdrs, &objp->refresh_token))
		 return FALSE;
	return TRUE;
}
