/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OAUTH_H_RPCGEN
#define _OAUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct token {
	char *type;
};
typedef struct token token;

struct request {
	char *client_id;
	struct token token;
};
typedef struct request request;

struct response {
	char *message;
	struct token auto_token;
	struct token access_token;
	struct token refresh_token;
};
typedef struct response response;

#define OAUTH_PROG 0x33445566
#define OAUTH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define request_autorization 1
extern  struct response * request_autorization_1(struct request *, CLIENT *);
extern  struct response * request_autorization_1_svc(struct request *, struct svc_req *);
#define request_approve 2
extern  struct response * request_approve_1(struct request *, CLIENT *);
extern  struct response * request_approve_1_svc(struct request *, struct svc_req *);
#define request_access_token 3
extern  struct response * request_access_token_1(struct request *, CLIENT *);
extern  struct response * request_access_token_1_svc(struct request *, struct svc_req *);
#define validate_delegated_action 4
extern  struct response * validate_delegated_action_1(struct request *, CLIENT *);
extern  struct response * validate_delegated_action_1_svc(struct request *, struct svc_req *);
extern int oauth_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define request_autorization 1
extern  struct response * request_autorization_1();
extern  struct response * request_autorization_1_svc();
#define request_approve 2
extern  struct response * request_approve_1();
extern  struct response * request_approve_1_svc();
#define request_access_token 3
extern  struct response * request_access_token_1();
extern  struct response * request_access_token_1_svc();
#define validate_delegated_action 4
extern  struct response * validate_delegated_action_1();
extern  struct response * validate_delegated_action_1_svc();
extern int oauth_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_token (XDR *, token*);
extern  bool_t xdr_request (XDR *, request*);
extern  bool_t xdr_response (XDR *, response*);

#else /* K&R C */
extern bool_t xdr_token ();
extern bool_t xdr_request ();
extern bool_t xdr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OAUTH_H_RPCGEN */
