/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

struct ser_response *
request_autorization_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct ser_response *
request_approve_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct ser_response *
request_access_token_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct ser_response *
validate_delegated_action_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct ser_response *
refresh_access_token_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}
