/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

struct token create_token() {
	struct token new_token;
	new_token.type = "Empty token";
}

struct response *
request_autorization_1_svc(struct request *argp, struct svc_req *rqstp)
{
	static struct response  result;

	/*
	 * insert server code here
	 */
	result.message = "Message";
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	return &result;
}

struct response *
request_approve_1_svc(struct request *argp, struct svc_req *rqstp)
{
	static struct response  result;

	/*
	 * insert server code here
	 */

	result.message = "Message";
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	return &result;
}

struct response *
request_access_token_1_svc(struct request *argp, struct svc_req *rqstp)
{
	static struct response  result;

	/*
	 * insert server code here
	 */

	result.message = "Message";
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	return &result;
}

struct response *
validate_delegated_action_1_svc(struct request *argp, struct svc_req *rqstp)
{
	static struct response  result;

	/*
	 * insert server code here
	 */

	result.message = "Message";
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	return &result;
}
