/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"
#include "helpers_server.h"
#include "token.h"

struct tokken create_token() {
	struct tokken new_token;
	new_token.type = "Empty token";
	return new_token;
}

char *string_to_char(std::string str) {
	char *cstr = (char *)calloc(str.length() + 1, sizeof(char));
	strcpy(cstr, str.c_str());
	return cstr;
}

// TODO:continue from here
struct ser_response *
request_autorization_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	// Generate default tokens
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	std::string user_id = argp->client_id;
	if (users.find(user_id) == users.end()) {
		result.message =  "USER_NOT_FOUND";
		return &result;
	}
	
	char *auto_token = generate_access_token(string_to_char(user_id));
	result.auto_token.type = strdup(auto_token);
	result.message = "USER_FOUND";

	return &result;
}

struct ser_response *
request_approve_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	result.message = "Message";
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	return &result;
}

struct ser_response *
request_access_token_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	result.message = "Message";
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	return &result;
}

struct ser_response *
validate_delegated_action_1_svc(struct cl_request *argp, struct svc_req *rqstp)
{
	static struct ser_response  result;

	/*
	 * insert server code here
	 */

	result.message = "Message";
	result.auto_token = create_token();
	result.access_token = create_token();
	result.refresh_token = create_token();

	return &result;
}
